### ISSUE TITLE
Storycards: public vs private

### ISSUE THREAD

**Issue by wimpers** [Incubaid/dev_process#10]
Kristof,

I have been thinking about the problem we discussed about the community having a view on the public storycards of the Open vStorage project. On the other hand it makes sense to have private storycards for certain items which community members can't see. 

I would like to propose the following:
- (public) Storycards which are of interest for the opensource community get logged under the public home repo
- (private) Storycards which are private/proprietary get logged under org_dev (which is a private repo)

I believe this could work since developers should use Waffle to have a view on what their work/storycards are. This means that our engineers  will see  on the waffle both the public and private storycards in a single view (all the work). In case a community members logs in he/she will see only the public storycards in the home repo in Waffle. What do you think?

**Comment by despiegk** [comment]
can we use the FR on home repo?
I think I roadmap can be created that way

personally I would prefer to keep stories internal to company

**Comment by wimpers** [comment]
FR on the home repo are ok.

The only drawback is that the community can't follow up on the progress or the (internal) discussion of the implementation.

**Comment by despiegk** [comment]
They can discuss on the higher level fr
