### ISSUE TITLE
Story group meetings

### ISSUE THREAD

**Issue by FastGeert** [Incubaid/dev_process#14]
We need a way to declare when a story group meeting is being held, and which stories are covered.

The goal is to make it clear for people that are interested to attend where, when & how they can attend.

Proposal: Use the following 8 labels to declare when the story group meeting is being held for a certain story:
- stgm-10:00-amcet
- stgm-10:30-amcet
- stgm-11:00-amcet
- stgm-11:30-amcet
- stgm-2:00-pmcet
- stgm-2:30-pmcet
- stgm-3:00-pmcet
- stgm-3:30-pmcet

Per story group meeting also a fixed zoom will be created so that people easily can join this zoom to join the story group meeting

**Comment by despiegk** [comment]
don't understand shouldn't we use the telegram milestone group, see doc, lots of improvements

**Comment by FastGeert** [comment]
Well the fact that story meetings do not have a fixed hour on when they are held is a problem. They should not be held all at the same time, but at this point it is very unclear when / if they are being held.

**Comment by despiegk** [comment]
obsolete
