### ISSUE TITLE
Funnel issues

### ISSUE THREAD

**Issue by wimpers** [Incubaid/dev_process#18]
We are trying to follow the process at Open vStorage as outlined in https://gig.gitbooks.io/agile/content/funnel.html.

Some issues:
- Features are typically not related to a only a single specif code repo. For example changes on ALBA require integration by the Framework team.
- Customers and team members set already priority labels. We can tell team members not to set the priority but we don't have control over customers. Having team members giving an indication of the severity of the bug is a good help for the [productowner](roles.md) to define the priority as severity and priority are interlinked. 
- There is no way as product owner to know which bugs are new. (Basing this on priority labels being there or not is not working for us) 
- I'm a bit confused. Should we add bugs/FR to a storycard or just add them to a milestone? 
  - 'OUT: Stories' at the top
  - the bugs or FR's are grouped and planned to be executed (attached to milestones)
  - these milestones are used to link X nr of bugs/FR's to a story in the milestone repo

Proposal:
- Add label state_qualified
  - Set by [productowner](roles.md) to acknowledge that he has seen the bug and everything is clear (necessary logs are for example attached) so he can make a judgement call on the priority.
  - Engineers only work on qualified bugs based on priority.
  - It would make it easy for the BAM to see which bugs are still to be tackled by the BAM (those without state_qualified) 
- Maybe we should have a 0 bug policy http://galzellermayer.blogspot.be/2013/05/0-bugs-policy.html

**Comment by despiegk** [comment]
see the faq, I think that should resolve it.
- features can be a story
- features can be a FR on home repo level if done by external person or e.g. prod mgr to expose a roadmap
- customer if they are contributors can set levels
- about new bugs? there is a date to it? and priorities can be set? dont understand

**your 0-bug suggestion is now part of our process**

**Comment by despiegk** [comment]
please re-read the docs, your feedback was very valuable, I hope I have most covered now
