### ISSUE TITLE
Ticket Tasks

### ISSUE THREAD

**Issue by wimpers** [Incubaid/dev_process#19]
Some issues with https://gig.gitbooks.io/agile/content/tickets_tasks.html
- Bugs can be raised by customers in our case. We even receive PRs (f.e. https://github.com/openvstorage/openvstorage-health-check/pull/34) for improvement
- If someone tumbles upon a blocking bug, why not set the label accordingly?
- FR typically span multiple repos in our case. Should they now be added to storycards or not?

**Comment by despiegk** [comment]
most answered in
https://gig.gitbooks.io/agile/content/faq.html

about blocking bug: depends on who reports, someone with enough rights can set this?
