### ISSUE TITLE
This is a fake story (story1)

### ISSUE THREAD

**Issue by despiegk** [Incubaid/dev_process#21]
## GOAL:

Clearly describe the goal what needs to be achieved when the story is delivered.
## DESCRIPTION:

Describe what story is about
## LINKS:
- tasks: [kanban](https://waffle.io/gig-projects/org_development?search=tasks:&label=type_task)
- specs: [link to the markdownpage holding the specifications for the story](http://foo.com)
- repositories involved:
  - [Jumpscale/github_automation](https://github.com/Jumpscale/github_automation)
  - [0-complexity/openvcloud](https://github.com/0-complexity/openvcloud)
## REQUIREMENTS:
- Specify requirements
- IMPORTANT
## REMARKS:

Add remarks
## ESTIMATION:

Estimation is optional and ONLY SET BY THE STORY CARD OWNER 
It is an assessment from story card owner to visualize the initial amount of hours/days needed to deliver this story, is aggregated mandays/hours for all people working on this

**ESTIMATION**: 4d

**Comment by FastGeert** [comment]
ETA: 20/06/2016
Almost code complete, need to start documenting
