### ISSUE TITLE
process_notreproducible

### ISSUE THREAD

**Issue by wimpers** [Incubaid/dev_process#33]
Can we add process_notreproducible . You want to make a distinction between process_wontfix and can't reproduce it anymore.

**Comment by wimpers** [comment]
https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/ you can find some more interesting labels we could add: under discussion f.e.

**Comment by despiegk** [comment]
think its too complex
please reread our docs, should be more easy now
