### ISSUE TITLE
milestone blueprint - use actual dates 

### ISSUE THREAD

**Issue by wimpers** [Incubaid/dev_process#35]
Currently a milestone is defined as below

> github_milestone__GeoScale:
>   milestone.description: 'GeoScale code complete'
>   milestone.deadline: '+1m'
>   milestone.owner: 'wimpers'
>   milestone.category: 'code_ovs''+1m'

Can we make the deadline an actual date as the '+1m' is confusing. 
-  There is no way to set the exact date. You typically want to define the end date as a Friday or end of the month.
-  Based upon this blueprint you can't say if the milestone is still relevant.
-  Updating the deadline data becomes hard. Let's say we are already a few days (f.e. a week) later compared to when the milestone was created. And I want to extend it with a week. Should I say '1m+1w'? Or Should I deduct the days which are passed already and set it to '1m' but that was the odl value so how can the cockpit script know I want to update the field?

**Comment by wimpers** [comment]
@despiegk @FastGeert can this one be picked up. Once in place, can we run the cockpit script on the ovs repo's?

**Comment by yveskerwyn** [comment]
As a follow-up on this I made the planning section more verbose/clarifying.

@wimpers @FastGeert @despiegk thanks for reviewing the pull request: https://github.com/Incubaid/dev_process/compare/language_and_format_check?expand=1

**Comment by despiegk** [comment]
too complex, went away from milestone meetings, ...
