### ISSUE TITLE
Repo naming convention proposal: Use env_ prefix for all environment repos

### ISSUE THREAD

**Issue by yveskerwyn** [Incubaid/dev_process#37]
So:
be-scale-1 -> env_be-scale-1
be-scale-2 -> env_be-scale-2
...

**Comment by lzonneke** [comment]
Can we also define the project...

We install them in the 0-complexity repo right?
This has impact on the install script of @maxux

**Comment by maxux** [comment]
This is not a good idea for me.
By convention, we used the repository name to be the same as the environment name. I think few blocks of code use this logic and this would break some code. Not only the installer.

A better way for me would use an organisation (I'm not sur about the name) for environments. Like `gig-environments/be-scale-1` for exemple, and not keep them on 0-complexity's organisation.

We put them on `0-complexity` the first time because we didn't know where to put them with private option available. Now github's private repository policies changed, we can review something better ?

**Comment by yveskerwyn** [comment]
I'm in to move the env repos into a new organization

**Comment by lzonneke** [comment]
so what was discussed this morning is that we will have all our environments available on the gig-projects repo.

For every customer there is a `proj_repo`

an environment GIT repo needs to run on the master of the specific environment. In this repo we should have all the available information of that specific environment including:
- installed version
- installed hardware
- configured network
- ....

So for our internal environments we indeed should make a repo called eg. `proj_greenitglobe_env`

For each environment owned by GIG we should have a separate folder with the name of that environment. 
In the `readme.md` file of that folder there should be a link to the environment repo which is located on the master of that environment. 

@FastGeert @hofkensj 

We all agree on that?

**Comment by maxux** [comment]
If proj_greenitglobe_env is an organisation and not a repository like you
say, okay, otherwise that means that all environment will use the same repo
and use specific folder on it ?

**Comment by lzonneke** [comment]
proj_gig_env should be a repo of the gig-projects organisation, 
We have a repo per customer called proj_customername, in this repo we should store the environment information of that customer in a dedicated environment folder.

The aim is to handle our environments like we should do for a customer project. Like this we test the full process.

**Comment by maxux** [comment]
That mean that all environment from the same customer got the information
from others environment... Is that not a security issue ?

**Comment by lzonneke** [comment]
ok yes, as discussed, this would not be how we want this....

we have agreed on creating a repo per environment on the gig-projects organisation

## Environment repo naming

repo naming convention should be
**env_$customername_$environmentname**

the $environmentname has the following naming convention
**$countrycode - $G8type - $environmentnumber**

$G8type can be
_scale_ = for scaleout environments (separate CPU 1U nodes (1 motherboard per server) which are scale able, storage and CPU all in one unit)

_conv_ = converged environment (multiple nodes in one system eg. 4+ nodes in one physical box with shared backplane.  Storage + multiple CPU nodes in one box)

_stor_ = for environments which are using +2 storage nodes with a minimum CPU config (5 nodes)

_G8_ = for our G8 configs (CPU + separate storage on 70 disk nodes)

## Cockpit repo naming

When there needs to be a cockpit deployed we need to create another separate repo for that operator.
naming convention should be

**cockpit_$customername_$purpose**

$customername = the reseller of the operator capacity, or "gig" for internal use
$purpose = a short useful name which describes the cockpit function

eg. 
- _git_ (for our internal gitrobot)
- _resell_ (when we have a reseller)
- _demo_ (cockpit for demo purposes)

@FastGeert 
@hofkensj

pleas comment, if no comment we will add in the agile process

**Comment by yveskerwyn** [comment]
I've updated the Agile guidelines with this information, it's part of my last pull request.

Thanks for reviewing the pull request:
https://github.com/Incubaid/dev_process/pull/38/files

**Comment by despiegk** [comment]
now is moved to become cockpit_... repo's

**Comment by yveskerwyn** [comment]
cockpit_ and env_ is not the same, or is it @despiegk ?

**Comment by grimpy** [comment]
@yveskerwyn env_ is for g8 installed by ays7 (which does not relate to a cockpit (yet))
