### ISSUE TITLE
Home/milestone repo -> issues types used

### ISSUE THREAD

**Issue by wimpers** [Incubaid/dev_process#4]
I propose to have more issues types used on the home/milestone repo:
- bug: it is hard for users to know where exactly an issue is located and it might require work in 2 repos to fix the issue. For example and ASD issue might require work on the ALBA repo and on the ASD manager repo
- feature request (FR): a feature request might involve work on 2 repos. I would see the feature request on the home repo as place where the work across these both repos can be viewed.
- roadmap item: collection of FRs

**Comment by despiegk** [comment]
please see new docs, I think it should be resolved now
