### ISSUE TITLE
QA and CI

### ISSUE THREAD

**Issue by wimpers** [Incubaid/dev_process#42]
I would like to check if I'm correct with an assumption. If correct we might want to update the documentation accordingly as now it is a loophole.

I assume that when a ticket is in the 'Verification' state, the code isn't merged in (PR is open). Once QA gives his approval the PR is merged in. Having QA approval is the only way to be able to work with a stable trunk. 

@despiegk can you confirm?

A second question is how this related to Continuous Integration testing (CI). I assume that CI testing should happen on the feature branch before the PR is merged in? Doing it after the merge is risky as the whole project might be broken for quite a long time in case there is a major issue. For me a feature or bug can only be closed if the code + the tests are adjusted. This means that QA moves the state from 'Verification' to Closed.

**Comment by despiegk** [comment]
QA gets implemented differently in every organization, this is part of the last step, ofcourse anyone can implement them how they see fit

**Comment by despiegk** [comment]
there is going to be a new document about branching
