### ISSUE TITLE
Request for an additional state

### ISSUE THREAD

**Issue by wimpers** [Incubaid/dev_process#43]
I'm having some difficulties to implement the flow as suggested by Incubaid Agile Development Conventions at Open vStorage. The issue is mainly caused because we have a separate QA team (manual and QA tests).

The flow we have now implemented is:
- Engineer pick up the storycard to work upon
- Once complete he create a PR (PR is automatically checked for some basic QA to check if it doesn't break anything we currently have).
- The PR gets reviewed and merged (We don't want to merge the PR too late as this will lead to many feature branches which need to be updated). 
- Reviewer puts the storycard in validation for QA.
- QA creates the necessary new tests and validates.
- All tests pass, QA closed the storycard.

I'm not happy with this last step as this means QA closes the storycard and not the storycard holder. The issue is that we have a state passing 'QA passed'. Instead of moving from validation to closed, QA would move from validation to 'QA passed'. IN that case the storycard owner knows it is up to him to verify it everything is according to his expectations and he closes the storycard.

Note that in future we will make sure there are autotests before the PR can be merged and this will be blocking.

**Comment by despiegk** [comment]
we have a validation step, specs changed a lot, best to review
