### ISSUE TITLE
What is a milestone?

### ISSUE THREAD

**Issue by wimpers** [Incubaid/dev_process#6]
Is a milestone a sprint? Or is it a release? Since it is tied to a storycard I would say sprint but I believe it would make sense to clearly define this.

I'm also a bit confused that features get assigned to a milestone (so sprint if we use the above definition). I always assumed these were assigned to a release?

**Comment by despiegk** [comment]
have reworked heavily in doc, please re-read and let me know if better now.
but basically
- milestone is a time event on projorg (see doc)
- milestone is a release on prodorg

there are max 3
